[features]
seeds = false
skip-lint = false
[programs.localnet]
ft_trading = "S3T2JExjrp6a48LNcxNxBHKa1GTB3bXRmwH3wepB5KQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "update_auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
