[features]
seeds = false
skip-lint = false
[programs.localnet]
ft_trading = "SETaVQKfUNLS2xUR61uauMTptRdKyaKHfPYjDvHAnxv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "update_auth.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
